on:
  workflow_dispatch:
jobs:
    Example:
      runs-on: ubuntu-latest
      steps:
        - run: |
            deprecated: true
            if: [[deprecated]] ; then
            echo: "::warning::Deprecated function is found"
            fi
            
            
