
on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"

  pull_request:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"

jobs:
    example-jobs:
          runs-on: ubuntu-latest
          
          steps :
          - name: print-welcome-message
            run: echo "welcome to our first workflow on GitHub!"
          - name:  checkout-repo
            uses: actions/checkout@v6.0.2
          - name: list all dic
            run: ls -la
